development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  pool: 5
  host: <%= ENV["OPENSHIFT_POSTGRESQL_DB_HOST"] %>
  database: <%=ENV['OPENSHIFT_APP_NAME']%>
  username: <%=ENV['OPENSHIFT_POSTGRESQL_DB_USERNAME']%>
  password: <%=ENV['OPENSHIFT_POSTGRESQL_DB_PASSWORD']%>
  socket:   <%=ENV['OPENSHIFT_POSTGRESQL_DB_SOCKET']%>

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  pool: 5
  host: <%= ENV["OPENSHIFT_POSTGRESQL_DB_HOST"] %>
  database: <%=ENV['OPENSHIFT_APP_NAME']%>
  username: <%=ENV['OPENSHIFT_POSTGRESQL_DB_USERNAME']%>
  password: <%=ENV['OPENSHIFT_POSTGRESQL_DB_PASSWORD']%>
  socket:   <%=ENV['OPENSHIFT_POSTGRESQL_DB_SOCKET']%>

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: natal_charts_production
#   pool: 5
#   username: polestar
#   password: sourdough
#   host: localhost
#   port: 5432

test:
  adapter: sqlite3
  database: ':memory:'
  pool: 5
  timeout: 5000
