# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

# development:
#   adapter: sqlite3
#   encoding: unicode
#   database: db/development.sqlite3

production:
  adapter: postgresql
  encoding: unicode
  database: polestar_astrology_production
  host: localhost
  pool: 5
  username: polestar_astrology
  password: idly_and_sambar

# test:
#   adapter: sqlite3
#   encoding: unicode
#   database: db/test.sqlite3

development:
  adapter: postgresql
  encoding: unicode
  database: polestar_astrology_development
  # host: localhost
  pool: 50
  # username: dbuser
  # password: sourdough
  # adapter: postgresql
  # encoding: unicode
  # database: polestar_astrology_production
  # host: localhost
  # pool: 100
  # username: polestar_astrology
  # password: "[6!NGk]Gka3zb5,,s4"


test:
  adapter: postgresql
  encoding: unicode
  database: polestar_astrology_test
  pool: 5
